stack_list=[]
stack_list.append("https://www.youtube.com")
stack_list.append("https://dobys.netlify.app/")
stack_list.append("https://www.google.com")
stack_list.append("https://www.github.com")
stack_list.append("https://www.reddit.com")
stack_list.append("https://www.facebook.com")
stack_list.append("https://www.instagram.com")
stack_list.append("https://www.twitter.com")
stack_list.append("https://www.linkedin.com")
stack_list.append("https://www.pinterest.com")
stack_list.append("https://www.tumblr.com")
stack_list.append("https://www.quora.com")
print("Stack List: ", stack_list)
print("Stack List Length: ", len(stack_list))
print("Stack List First Element: ", stack_list[0])
print("Stack List Last Element: ", stack_list[-1])
print("Stack List Second Element: ", stack_list[1])
print("Stack pop: ", stack_list.pop())
print("Stack List After Pop: ", stack_list)
print("Stack List Length After Pop: ", len(stack_list))
print("Stack List First Element After Pop: ", stack_list[0])
print("Stack List Last Element After Pop: ", stack_list[-1])
