from collections import deque
stack = deque()
stack.append("https://www.youtube.com")
stack.append("https://dobys.netlify.app/")
stack.append("https://www.google.com")
stack.append("https://www.github.com")
stack.append("https://www.reddit.com")
stack.append("https://www.facebook.com")
stack.append("https://www.instagram.com")
stack.append("https://www.twitter.com")
stack.append("https://www.linkedin.com")
stack.append("https://www.pinterest.com")
stack.append("https://www.tumblr.com")
stack.append("https://www.quora.com")
print("Stack Deque: ", stack)
print("Stack Deque Length: ", len(stack))
print("Stack Deque First Element: ", stack[0])
print("Stack Deque Last Element: ", stack[-1])
print("Stack Deque Second Element: ", stack[1])
print("Stack pop: ", stack.pop())
print("Stack Deque After Pop: ", stack)
print("Stack Deque Length After Pop: ", len(stack))
print("Stack Deque First Element After Pop: ", stack[0])
print("Stack Deque Last Element After Pop: ", stack[-1])
print("Stack Deque Second Element After Pop: ", stack[1])